// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpyasttvqzornqrvksog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJweWFzdHR2cXpvcm5xcnZrc29nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjYwMzYsImV4cCI6MjA2NTUwMjAzNn0.FTy_QCH7jESTjp4XSdf3n3z9Y_8-Ptd221GQqFeXz3s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);